result: structure.c
	$(CC) structure.c -o result	-Wall -Wextra -pedantic -std=c99

structINstruct: structINstruct.c
	$(CC) structINstruct.c -o structinstruct	-Wall -Wextra -pedantic -std=c99

arr_of_struct: arr_of_structures.c
	$(CC) arr_of_structures.c -o arr_of_struct 	-Wall -Wextra -pedantic -std=c99

pointer: pointer_to_struct.c 
	$(CC) pointer_to_struct.c -o pointer 	-Wall -Wextra -pedantic -std=c99

function: function.c 
	$(CC) function.c -o s_function 	-Wall -Wextra -pedantic -std=c99
